name: context-demo
on: workflow_dispatch
jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: context-step
        run:  |
          echo: "who is trigger ${{github.actor}}"
          echo: "Repo name is ${{github.repository}}"
