name: demo2-practice
on: workflow_dispatch
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: build-stage
          run: 
            echo "build successful"
    test: 
       runs-on: ubuntu-latest
       steps:
         - name: test-stage
           run: 
             echo "test successful"

    deploy:
       runs-on: ubuntu-latest
       steps:
         - name: deploy-stage
           run: 
             echo "deply suuceesfully"
             
         

        
    
  
  
