name: demo2-practice
on: workflow_dispatch
jobs:
    Demo2-job:
      runs-on: ubuntu-latest
      steps:
        -  name: demo2-step
           run: |
             echo "one"
             echo "two"
  
  
  
