name: if-condition1
on: workflow_dispatch
jobs:
  if-condition-job:
    runs-on: ubuntu-latest
    steps:
      - name: valid-user
        if: github.actor == 'arif511bash'
        run: echo "you are the right person"

      - name: invalid-user
        if: github.actor != 'arif511basha'
        run: echo 'not a valid user'
        
